### PR TITLE
Fix search.maxLimit configuration 

### LINKED ISSUE #532: search.maxLimit is not working in UI
## Requirement - what kind of business use case are you trying to solve?

`search.maxLimit` is not working, it doesn't respect the configured value.

## Problem - what in Jaeger blocks you from solving the requirement?

This was reported in: https://github.com/jaegertracing/jaeger/issues/2087

### PR DESCRIPTION
**Pull request by rubenvp8510**
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

## Which problem is this PR solving?
- Fixes #532 

## Short description of the changes
- now the `getConfigValue` is used instead of the default exported `getConfig`

### CODE REVIEW

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ import * as jaegerApiActions from '../../actions/jaeger-api';
 import { formatDate, formatTime } from '../../utils/date';
 import reduxFormFieldAdapter from '../../utils/redux-form-field-adapter';
 import { DEFAULT_OPERATION, DEFAULT_LIMIT, DEFAULT_LOOKBACK } from '../../constants/search-form';
-import getConfigValue from '../../utils/config/get-config';
+import { getConfigValue } from '../../utils/config/get-config';
```
Comment (yurishkuro) [inline packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js]: should there be a unit test that would catch this?

Comment (satmurat) [reply packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js]: Also, here maybe problem with build, package, dockerize etc. Because I did not see this deleted 37th row, when I am debugging in Chrome. I suggest testing after building into docker.

Comment (rubenvp8510) [reply packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js]: I'll add tests.

**Comment by rubenvp8510** [comment]
Tests added.

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js (hunk 1 above)
Comment (yurishkuro) [reply packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js]: Docker image contains JS transpiled to ES5. I'd assume the code to look very different there (also minified).

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js [hunk 2]
```diff
@@ -392,6 +392,19 @@ describe('<SearchForm>', () => {
     btn = wrapper.find(`[data-test="${markers.SUBMIT_BTN}"]`);
     expect(btn.prop('disabled')).toBeTruthy();
   });
+
+  it('uses config.search.maxLimit', () => {
+    const maxLimit = Math.floor(Math.random() * 7000) + 3000;
```
Comment (yurishkuro) [inline packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js]: a fixed constant would do just as well, e.g. 1234 (unlikely to be the default value elsewhere)

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js [hunk 3]
```diff
@@ -392,6 +392,19 @@ describe('<SearchForm>', () => {
...
+    const config = {
+      search: {
+        maxLimit,
+      },
+    };
+    window.getJaegerUiConfig = jest.fn(() => config);
+    wrapper = shallow(<SearchForm {...defaultProps} selectedService="svcA" />);
+    const field = wrapper.find(`Field[name="resultsLimit"]`);
+    expect(field.prop('props').max).toEqual(maxLimit);
```
Comment (yurishkuro) [inline packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js]: did you confirm that this test breaks without the fix above?

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js (hunk 2 above)
Comment (rubenvp8510) [reply packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js]: Ok, I'll use a constant.

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js (hunk 3 above)
Comment (rubenvp8510) [reply packages/jaeger-ui/src/components/SearchTracePage/SearchForm.test.js]: Yes

Without this fix:

Error: expect(received).toEqual(expected)

Expected value to equal:
  4854
Received:
  {"archiveEnabled": false, "dependencies": {"dagMaxNumServices": 100, "menuEnabled": true}, "linkPatterns": [], "menu": [{"items": [{"label": "GitHub", "url": "https://github.com/uber/jaeger"}, {"label": "Docs", "url": "http://jaeger.readthedocs.io/en/latest/"}, {"label": "Twitter", "url": "https://twitter.com/JaegerTracing"}, {"label": "Discussion Group", "url": "https://groups.google.com/forum/#!forum/jaeger-tracing"}, {"label": "Gitter.im", "url": "https://gitter.im/jaegertracing/Lobby"}, {"label": "Blog", "url": "https://medium.com/jaegertracing/"}], "label": "About Jaeger"}], "search": {"maxLimit": 4854, "maxLookback": {"label": "2 Days", "value": "2d"}}, "tracking": {"gaID": null, "trackErrors": true}}

File: packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js (hunk 1 above)
Comment (satmurat) [reply packages/jaeger-ui/src/components/SearchTracePage/SearchForm.js]: image
screenshot from chrome devtools.

**Comment by pavolloffay** [comment]
@rubenvp8510 is this ready to be merged? 

@yurishkuro can this be merged so 1.17.1 can be released?

**Comment by rubenvp8510** [comment]
@pavolloffay  if there is no more comments, is ready.
