### PR TITLE
Fix the tooltip position of copy value and JSON Buttton

### LINKED ISSUE #1649: [Bug]: Change the tooltip position of Copy value & json
### What happened?

After hovering over the 'Copy JSON' button, I am unable to access the 'Copy Value' button. The tooltip of the 'Copy JSON' button is blocking the 'Copy Value' button.

### Steps to reproduce

1.Hover over the copy json button

### Expected behavior

It would be better if the tooltip were positioned at the top or if the value of mouseLeaveDelay is 0.

### Relevant log output

_No response_

### Screenshot

Screenshot 2023-08-09 023328

### Additional context

_No response_

### Jaeger backend version

_No response_

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

_No response_

### PR DESCRIPTION
**Pull request by anikdhabal**
fix #1649 

Screenshot 2023-08-09 045507

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality

### CODE REVIEW

File: packages/jaeger-ui/src/components/common/CopyIcon.tsx [hunk 1]
```diff
@@ -64,7 +64,7 @@ export default class CopyIcon extends React.PureComponent<PropsType, StateType>
     return (
       <Tooltip
         arrowPointAtCenter
-        mouseLeaveDelay={0.1}
+        mouseLeaveDelay={0}
```
Comment (yurishkuro) [inline packages/jaeger-ui/src/components/common/CopyIcon.tsx:67]: why?

Comment (anikdhabal) [reply packages/jaeger-ui/src/components/common/CopyIcon.tsx:67]: Because of this-

https://github.com/jaegertracing/jaeger-ui/assets/81948346/4e515d4c-6247-4cc5-a8db-0230b610a96d

Comment (anikdhabal) [reply packages/jaeger-ui/src/components/common/CopyIcon.tsx:67]: @yurishkuro what do you think?

**Review by yurishkuro — DISMISSED** [review]
thanks

**Comment by yurishkuro** [comment]
You may need to regenerate the snapshots `yarn test -u`

**Review by bupd — COMMENTED** [review]
Congrats!!

**Comment by yurishkuro** [comment]
CI is still failing

**Comment by anshgoyalevil** [comment]
@anikdhabal You would need to run `yarn test -u` inside the packages/jaeger-ui` directory.

**Comment by anikdhabal** [comment]
> @anikdhabal You would need to run `yarn test -u` inside the packages/jaeger-ui` directory. The changes made (Snapshots are updated automatically bts) thereafter would need to be committed to this PR.

Yeah, thanks man.

**Comment by anikdhabal** [comment]
> You may need to regenerate the snapshots `yarn test -u`

Done

**Review by yurishkuro — APPROVED** [review]
