### PR TITLE
Fix: Clicking dots and DDG button

### LINKED ISSUE #3111: [Bug]: "Deep Dependency Graph" button is not responding when clicked
### What happened?

The "Deep Dependency Graph" button in the Jaeger UI is not responding when clicked. Users cannot access the DDG view from the search results page.

### Steps to reproduce

1. Navigate to Jaeger UI search page
2. Perform a trace search to get results
3. Look for the "Deep Dependency Graph" button in the search page and click it
4. Observe that nothing happens or the button doesn't respond

### Expected behavior

Clicking the "Deep Dependency Graph" button should switch the view from trace list to DDG view

### Relevant log output

```shell

```

### Screenshot

Image

### Additional context

_No response_

### Jaeger backend version

_No response_

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

```shell

```

### PR DESCRIPTION
**Pull request by ghost**
## Which problem is this PR solving?
- Resolves #3111 and https://github.com/jaegertracing/jaeger-ui/issues/3123#issuecomment-3431088792

## Description of the changes
- Replaced `history` with `useNavigate()` hook and converted `goToTrace` to `useCallback`.

https://github.com/user-attachments/assets/39df0d58-c3aa-4e71-8cbd-3cabe717db5e

## How was this change tested?
- Unit tests

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: packages/jaeger-ui/src/components/SearchTracePage/index.jsx [hunk 1]
```diff
@@ -147,7 +147,6 @@ export class SearchTracePageImpl extends Component {
               cohortRemoveTrace={cohortRemoveTrace}
               diffCohort={diffCohort}
               disableComparisons={embedded}
-              goToTrace={this.goToTrace}
```
Comment (yurishkuro) [inline packages/jaeger-ui/src/components/SearchTracePage/index.jsx:150]: so what happens to `this.goToTrace` now? Is that function no longer needed?

Comment (ghost) [reply packages/jaeger-ui/src/components/SearchTracePage/index.jsx:150]: yes, it's no longer needed. Now `SearchResults` has its own `goToTrace` in `SearchResults/index.tsx`.

Comment (ghost) [reply packages/jaeger-ui/src/components/SearchTracePage/index.jsx:150]: there are some deadcodes i will remove them.

**Comment by ghost** [comment]
The failed scatterplot tests are not actually related to my changes, but these tests were failing previously in my local. so i fixed them

**Review by yurishkuro — APPROVED** [review]
