### PR TITLE
Handle Error stored in redux trace.traces

### LINKED ISSUE #166: JS error on search page after viewing 404 trace
**Description**

Navigating from a trace page that is 404 (trace not found) to the search page results in a JS error.

**Steps to reproduce the issue:**
1. Visit a trace page that does not exist, e.g. `/trace/000`
2. Click the "Search" button in the top nav

**Describe the results you received:**

The page does not change and the following JS error is logged:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at o (search.js:43)
    at Array.map (<anonymous>)
    at a (search.js:88)
    at index.js:209
    at get-last-xform-cacher.js:38
    at Function.a [as mapToProps] (index.js:232)
    at r (wrapMapToProps.js:43)
    at Function.r.mapToProps (wrapMapToProps.js:52)
    at r (wrapMapToProps.js:43)
    at o (selectorFactory.js:26)
```

**Describe the results you expected:**

The search page is presented without error.

### PR DESCRIPTION
**Pull request by tiffon**
Fix #166.

HTTP responses >= 400 (.e.g. 404s) cause an `Error` to be added to the redux store in `trace.traces[traceID]`. This PR prevents the search page from treating them as a normal trace.

### CODE REVIEW

**Comment by tiffon** [comment]
@simonrobb can you look this over when you get the chance?

File: src/model/search.js [hunk 1]
```diff
@@ -83,7 +86,7 @@ export function getTraceSummary(trace: Trace): TraceSummary {
  * @return {TraceSummaries} The `{ traces, maxDuration }` value.
  */
 export function getTraceSummaries(_traces: Trace[]): TraceSummaries {
-  const traces = _traces.map(getTraceSummary);
+  const traces = _traces.map(getTraceSummary).filter(Boolean);
```
Comment (yurishkuro) [inline src/model/search.js]: not sure I am following the typing here: `_traces` is an array of `Trace` objects, how could `getTraceSummary` function be called with an `Error` object?

Comment (tiffon) [reply src/model/search.js]: It's an inefficiency or irregularity in the state of static typing in the repo. Some files have flow-types and some do not. 

The type here is really `(Trace | Error)[]`.

Comment (yurishkuro) [reply src/model/search.js]: so maybe the fix should be (using Scala-ish notation)
```
_traces.filterNot(_ instanceof Error).map(getTraceSummary);
```
?

or even do the filtering somewhere upstream, instead of propagating the mixed type deeper.

Comment (simonrobb) [reply src/model/search.js]: Agreed. At the least, if it's possible for there to be `Error` objects present, the parameter type should be annotated like you described, `getTraceSummaries(_traces: (Trace | Error)[]): TraceSummaries`.

Comment (tiffon) [reply src/model/search.js]: @yurishkuro Great point. I will filter then get the summary. I don't want to filter it further upstream because the presence of the error will be useful in resolving #51.

@simonrobb 👍 

Note, the following code was not possible due to Flow flagging it as an error:

```js
const traces = _traces.filter(item => !(item instanceof Error)).map(getTraceSummary);
```
